name: GitHub Actions CD Demo
run-name: ${{ github.actor }} is testing out CD with self-hosted server
on: [workflow_dispatch]
jobs:
  GH-Actions-CD-Demo:
    runs-on: ubuntu-latest
    steps:
      # cloning repo...
      - name: Cloning repo...
        uses: actions/checkout@v3

      - name: Installing SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_TEST_CD }}
          known_hosts: 'placeholder'

      - name: ECHOing SSH_HOST_IP
        run: 'echo "$SSH_KEY" > key'
        env:
          SSH_KEY: ${{secrets.SSH_HOST_IP}}

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts

      - name: PWD
        run: pwd

      - name: Deploying with rsync
        run: echo "Deplying with rsync..."